"""empty message

Revision ID: f8fe5c0c244c
Revises: c55ec6b7a0a1
Create Date: 2021-03-22 08:30:43.061751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fe5c0c244c'
down_revision = 'c55ec6b7a0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('mon_from', sa.Time(), nullable=True),
    sa.Column('mon_to', sa.Time(), nullable=True),
    sa.Column('tue_from', sa.Time(), nullable=True),
    sa.Column('tue_to', sa.Time(), nullable=True),
    sa.Column('wed_from', sa.Time(), nullable=True),
    sa.Column('wed_to', sa.Time(), nullable=True),
    sa.Column('thu_from', sa.Time(), nullable=True),
    sa.Column('thu_to', sa.Time(), nullable=True),
    sa.Column('fri_from', sa.Time(), nullable=True),
    sa.Column('fri_to', sa.Time(), nullable=True),
    sa.Column('sat_from', sa.Time(), nullable=True),
    sa.Column('sat_to', sa.Time(), nullable=True),
    sa.Column('sun_from', sa.Time(), nullable=True),
    sa.Column('sun_to', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genres.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('venue_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True, default=False))

    # set seeking_venue for existing artists
    artists = sa.table('Artist',
        sa.column('seeking_venue', sa.Boolean),
    )
    op.execute(
        artists.update().values({'seeking_venue':op.inline_literal(False)})
    )

    op.alter_column('Artist', 'seeking_venue', existing_type=sa.Boolean(), nullable=False)
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.alter_column('Artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Artist', 'genres')
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True, default=False))

    # set seeking_venue for existing venues
    venues = sa.table('Venue',
        sa.column('seeking_talent', sa.Boolean),
    )
    op.execute(
        venues.update().values({'seeking_talent':op.inline_literal(False)})
    )

    op.alter_column('Venue', 'seeking_talent', existing_type=sa.Boolean(), nullable=False)
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.alter_column('Venue', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venue', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###

    # pre-populate genres
    genres = sa.table('Genres',
        sa.column('name', sa.String),
    )
    op.bulk_insert(genres,
        [
            {'name': 'Alternative'},
            {'name': 'Blues'},
            {'name': 'Classical'},
            {'name': 'Country'},
            {'name': 'Electronic'},
            {'name': 'Folk'},
            {'name': 'Funk'},
            {'name': 'Heavy Metal'},
            {'name': 'Hip-Hop'},
            {'name': 'House'},
            {'name': 'Instrumental'},
            {'name': 'Jazz'},
            {'name': 'Musical Theatre'},
            {'name': 'Pop'},
            {'name': 'Punk'},
            {'name': 'R&B'},
            {'name': 'Reggae'},
            {'name': 'Rock n Roll'},
            {'name': 'Soul'},
            {'name': 'Swing'},
            {'name': 'Other'},
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venue', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('Artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    op.drop_table('venue_genres')
    op.drop_table('artist_genres')
    op.drop_table('Shows')
    op.drop_table('Availability')
    op.drop_table('Genres')
    # ### end Alembic commands ###
